# Generated by Django 5.2.11 on 2026-02-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_remove_hotoffer_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='related_news',
            field=models.ForeignKey(blank=True, help_text='Ссылка на другую новость, которая будет отображаться в конце статьи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.news', verbose_name='Связанная новость'),
        ),
    ]
