# Generated by Django 5.2.11 on 2026-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_add_related_news_to_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='related_news',
        ),
        migrations.AddField(
            model_name='news',
            name='related_link_url',
            field=models.URLField(blank=True, help_text='URL на другую новость или внешний сайт (оставьте пустым, чтобы не показывать)', verbose_name='Ссылка в конце статьи'),
        ),
        migrations.AddField(
            model_name='newstranslation',
            name='related_link_title',
            field=models.CharField(blank=True, help_text='Подпись гиперссылки, которая отображается в конце статьи', max_length=300, verbose_name='Текст ссылки в конце'),
        ),
    ]
