# Generated by Django 5.2.11 on 2026-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_replace_related_news_with_link_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslation',
            name='related_link_title',
        ),
        migrations.AddField(
            model_name='news',
            name='related_link_title',
            field=models.CharField(blank=True, help_text='Текст, который будет кликабельным (например: «10 книг об искусстве»)', max_length=300, verbose_name='Заголовок ссылки в конце статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_link_url',
            field=models.URLField(blank=True, help_text='Адрес страницы — своей новости или внешнего сайта', verbose_name='URL ссылки в конце статьи'),
        ),
    ]
