# Generated by Django 5.2.11 on 2026-02-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_move_related_link_title_to_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('general', 'Общая услуга'), ('gazebo', 'Беседка')], default='general', help_text='Беседки выводятся отдельной секцией на странице услуг и связываются с картой', max_length=20, verbose_name='Категория'),
        ),
    ]
