# Generated by Django 5.2.11 on 2026-02-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_add_category_to_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.SlugField(help_text='Уникальный slug, например: berloga, besedka-6', max_length=80, unique=True, verbose_name='Идентификатор')),
                ('number', models.CharField(help_text='Текст внутри кружка на карте (например: 6, 8+1, 12)', max_length=20, verbose_name='Номер / метка на карте')),
                ('name', models.CharField(help_text='Всплывающая подсказка при наведении (например: Беседка на 6 мест)', max_length=200, verbose_name='Название')),
                ('left', models.FloatField(default=50, help_text='Горизонталь 0–100', verbose_name='Позиция X (%)')),
                ('top', models.FloatField(default=50, help_text='Вертикаль 0–100', verbose_name='Позиция Y (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('service', models.ForeignKey(blank=True, help_text='Страница услуги, которая откроется при клике на кружок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_areas', to='content.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Область карты',
                'verbose_name_plural': 'Области карты',
                'ordering': ['order', 'area_id'],
            },
        ),
    ]
