# Generated by Django 5.1.4

from django.db import migrations, models


def set_default_bank(apps, schema_editor):
    CompanyInfo = apps.get_model('content', 'CompanyInfo')
    for obj in CompanyInfo.objects.all():
        if not obj.bank_account and not obj.bank_name and not obj.bank_bic:
            obj.bank_account = 'BY20 MTBK 3012 0001 0933 0012 6296'
            obj.bank_name = 'ЗАО «МТБанк»'
            obj.bank_bic = 'MTBKBY22'
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_about_content_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Расчётный счёт (р/с)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.RunPython(set_default_bank, migrations.RunPython.noop),
    ]
