# Generated by Django 5.2.11 on 2026-03-13 14:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_companyinfo_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='long_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Редактор с форматированием: заголовки, списки, жирный текст и т.д.', verbose_name='Подробное описание'),
        ),
    ]
