# Generated by Django 5.2.11 on 2026-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_create_certificate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео (YouTube, Vimeo). Используется в блоке «Презентация турбазы» на странице «О нас».', verbose_name='Ссылка на видео'),
        ),
    ]
