# Generated by Django 4.2.28 on 2026-03-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_alter_aboutcontent_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsStatsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок статистики отзывов',
                'verbose_name_plural': 'Блок статистики отзывов',
            },
        ),
        migrations.CreateModel(
            name='ReviewsStatsContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('be', 'Беларуская'), ('en', 'English'), ('pl', 'Polski'), ('zh', '中文')], max_length=5)),
                ('distance_value', models.CharField(blank=True, max_length=50, verbose_name='Значение 1')),
                ('distance_label', models.CharField(blank=True, max_length=200, verbose_name='Подпись 1')),
                ('stat1_value', models.CharField(blank=True, max_length=50, verbose_name='Значение 2')),
                ('stat1_label', models.CharField(blank=True, max_length=200, verbose_name='Подпись 2')),
                ('stat2_value', models.CharField(blank=True, max_length=50, verbose_name='Значение 3')),
                ('stat2_label', models.CharField(blank=True, max_length=200, verbose_name='Подпись 3')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.reviewsstatscontent')),
            ],
            options={
                'verbose_name': 'Перевод блока статистики отзывов',
                'verbose_name_plural': 'Переводы блока статистики отзывов',
                'ordering': ['content', 'locale'],
                'unique_together': {('content', 'locale')},
            },
        ),
    ]
